apiVersion: v1
kind: Service
metadata:
  name: {{ template "mariadb.seviceName" . }}
spec:
  selector:
    app: {{ template "mariadb.labelApp" . }}
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
