{{- if or (empty .Values.mariadb.host) (empty .Values.mariadb.credentials.user) (empty .Values.mariadb.db.name)}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mariadb.configmapName" . }}
data:
  {{- if empty .Values.mariadb.host }}
  WORDPRESS_DB_HOST: {{ template "mariadb.seviceName" . }}
  {{- end }}
  {{- if empty .Values.mariadb.credentials.user }}
  WORDPRESS_DB_USER: user
  {{- end }}
  {{- if empty .Values.mariadb.db.name }}
  WORDPRESS_DB_NAME: database
  {{- end }}
{{- end }}