apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wp-mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.credentials.rootPassword | b64enc | quote }}
  MYSQL_DB_PASSWORD: {{ .Values.mariadb.credentials.wpPassword | b64enc | quote }}