apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mariadb-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mariadb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mariadb
    spec:
      containers:
      - name: mariadb
        image: {{ .Values.mariadb.image.name }}:{{ .Values.mariadb.image.tag }}
        volumeMounts:
          - name: mysql-volume
            mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "400Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-wp-mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-mysql-configmap
              key: WORDPRESS_DB_NAME
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-mysql-configmap
              key: WORDPRESS_DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-wp-mysql-secret
              key: MYSQL_DB_PASSWORD
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: pvc-mysql