apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-configmap
data:
  WORDPRESS_DB_HOST: {{ .Release.Name }}-mariadb-service
  WORDPRESS_DB_USER: {{ .Values.mariadb.credentials.user }}
  WORDPRESS_DB_NAME: {{ .Values.mariadb.db.name }}