{{- if or (empty .Values.mariadb.credentials.rootPassword) (empty .Values.mariadb.credentials.wpPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wp-mysql-secret
type: Opaque
data:
  {{- if empty .Values.mariadb.credentials.rootPassword }}
  MYSQL_ROOT_PASSWORD: {{ "insira-o-password" | b64enc | quote }}
  {{- end }}
  {{- if empty .Values.mariadb.credentials.wpPassword }}
  MYSQL_DB_PASSWORD: {{ "insira-o-password" | b64enc | quote }}
  {{- end }}
{{- end }}