apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
spec:
  selector:
    matchLabels:
      type: local
  storageClassName: pv-mysql
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi