apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "wordpress.pvName" . }}
  labels:
    type: local
spec:
  storageClassName: {{ template "wordpress.storageclassName" . }}
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /D/volumes/wp