apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "wordpress.pvcName" . }}
spec:
  selector:
    matchLabels:
      type: local
  storageClassName: {{ template "wordpress.storageclassName" . }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi