apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wordpress
spec:
  selector:
    matchLabels:
      type: local
  storageClassName: pv-wordpress
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi