apiVersion: v1
kind: Service
metadata:
  name: {{ template "wordpress.serviceName" . }}
spec:
  selector:
    app: {{ template "wordpress.labelApp" $ }}
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP