apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "wordpress.ingressName" . }}
spec:
  rules:
  {{- range .Values.wordpress.ingress }}
  - host: {{ . }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ template "wordpress.serviceName" $ }}
            port: 
              number: 80
  {{- end }}