apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wordpress.deploymentName" . }}

##Declaração das especificações do deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "wordpress.labelApp" . }}

##Declaração do template do deployment  
  template:
    metadata:
      labels:
        app: {{ template "wordpress.labelApp" . }}
##Especificação dos containers do pod
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image.name }}:{{ .Values.wordpress.image.tag }}
        ports:
        - containerPort: 80
        
##Politica de pull da imagem
        imagePullPolicy: Always

##Definindo resources
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "300m"
        
##Declaração ReadnessProbe - Check de quando o pod está pronto para receber trafego
        readinessProbe:
          httpGet:
            path: /wp-admin
            port: 80
            scheme: HTTP
          timeoutSeconds: 1
          failureThreshold: 3
          periodSeconds: 5
        
##Declaração StartupProbe - Check de quando o pod está up
        startupProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          timeoutSeconds: 1
          failureThreshold: 5
          periodSeconds: 5

##Declaração LivenessProbe - Healthcheck para garantir que o container está saudavel, caso não esteja o pod é reiniciado
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          timeoutSeconds: 1
          failureThreshold: 3
          periodSeconds: 5

##Declaração de volume e mounpoint no Pod
        volumeMounts:
          - name: volume-wp
            mountPath: /var/www/html
        
##Variáveis de ambiente utilizando configmap e secrets
        env:
        - name: WORDPRESS_DB_HOST
          {{- if empty .Values.mariadb.host }}
          valueFrom:
            configMapKeyRef:
              name: {{ template "mariadb.configmapName" . }}
              key: WORDPRESS_DB_HOST
          {{- else }}
          value: {{ .Values.mariadb.host }}
          {{- end }}
        - name: WORDPRESS_DB_USER
          {{- if empty .Values.mariadb.credentials.user }}
          valueFrom:
            configMapKeyRef:
              name: {{ template "mariadb.configmapName" . }}
              key: WORDPRESS_DB_USER
          {{- else }}
          value: {{ .Values.mariadb.credentials.user }}
          {{- end }}
        - name: WORDPRESS_DB_NAME
          {{- if empty .Values.mariadb.db.name }}
          valueFrom:
            configMapKeyRef:
              name: {{ template "mariadb.configmapName" . }}
              key: WORDPRESS_DB_NAME
          {{- else }}
          value: {{ .Values.mariadb.db.name }}
          {{- end }}
        - name: WORDPRESS_DB_PASSWORD
          {{- if empty .Values.mariadb.credentials.wpPassword }}
          valueFrom:
            secretKeyRef:
              name: {{ template "mariadb.secretName" . }}
              key: MYSQL_DB_PASSWORD
          {{- else }}
          value: {{ .Values.mariadb.credentials.wpPassword }}
          {{- end }}
##Declaração do volume disponivel para o pod
      volumes:
        - name: volume-wp
          persistentVolumeClaim:
            claimName: {{ template "wordpress.pvcName" . }}