apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress
  labels:
    type: local
spec:
  storageClassName: pv-wordpress
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /D/volumes/wp